project:
  type: website

website:
  title: "Mani_Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Mkamarapu
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

